### ISSUE TITLE
Build cleanup

### ISSUE THREAD

**Issue by jeromesimeon** [querycert/qcert#77]
Lots of development lead to a pretty unwieldy (and poorly) documented build process, along with inconsistent Makefiles, unclear directory structures, etc. Some improvements are badly needed. Among some of the most important ones:
- [x] Cleanup and integrate the Java part of the build process (#53)
- [x] Build query runners the same way we build other Java parts of the system
- [x] Remove java libraries that have been checked out, pull them from maven like the rest of them (#63)
- [x] Systematically build `bin/qcertJS.js` and make it independent from the native build for `bin/qcert`
- [x] Properly handle dependency of OCaml code to Coq code (`./ocaml/extracted`) shouldn't be recreated unless the Coq code has changed)
- [x] Automate and document the build process for the documentation (See also #68)
- [x] Provide a proper `make tests` target (See also #72)
- [x] Update the documentation for the build process in `README.md`

**Comment by jeromesimeon** [comment]
I'm declaring this round of cleanup closed.
